version: '3.8'

services:
  awwesome:
    image: ghcr.io/mkitzmann/awwesome:latest
    volumes:
      - data:/usr/src/app/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.awwesome.rule=Host(`beta.awweso.me`)"
        - "traefik.http.routers.awwesome.entrypoints=websecure"
        - "traefik.http.routers.awwesome.tls=true"
        - "traefik.http.services.awwesome.loadbalancer.server.port=3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - traefik

volumes:
  data:

networks:
  traefik:
    external: true
    name: traefik_traefik
